name: Build

on: [push]

jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 api/

  unit-test:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install Flask
          pip install pytest
      - name: Run pytest
        run: pytest api/

  coverage-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install coverage
        run: pip install coverage
      - name: Run coverage tests
        run: coverage run -m pytest api/
      - name: Generate coverage report
        run: coverage report -m
      
  build-and-push-image:
    needs: coverage-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2       
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            your-container-registry/your-image-name:latest
            your-container-registry/your-image-name:${{ github.sha }}